<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // High-volume, insert-only table, hence the plain bigint identity
        // PK instead of uuid. generatedAs() (no args) renders a real SQL
        // identity column (GENERATED BY DEFAULT AS IDENTITY), not a legacy
        // bigserial/nextval sequence default.
        Schema::create('page_views', function (Blueprint $table) {
            $table->id()->generatedAs();
            $table->foreignUuid('page_id')->constrained()->cascadeOnDelete();
            $table->timestampTz('viewed_at')->useCurrent();

            $table->index(['page_id', 'viewed_at']);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('page_views');
    }
};
