<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // High-volume, insert-only table, hence the plain bigint identity
        // PK instead of uuid. generatedAs() (no args) renders a real SQL
        // identity column (GENERATED BY DEFAULT AS IDENTITY), not a legacy
        // bigserial/nextval sequence default.
        Schema::create('block_clicks', function (Blueprint $table) {
            $table->id()->generatedAs();
            $table->foreignUuid('page_id')->constrained()->cascadeOnDelete();

            // Logical reference into pages.content JSONB — no FK by design.
            // Clicks on since-deleted blocks are ignored/grouped at read time.
            $table->text('block_id');

            $table->timestampTz('clicked_at')->useCurrent();

            $table->index(['page_id', 'block_id', 'clicked_at']);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('block_clicks');
    }
};
